# Generated by Django 3.2.5 on 2021-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Emailaddress', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=50)),
                ('Universityname', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
